### ISSUE TITLE
Suggestion: Incorrect information 

### ISSUE THREAD

**Issue by SoilentBrad** [WBHarry/pf2e-bestiary-tracking#1]
This is a brilliant module (though I haven’t had a chance to use it yet). Something that came to me is that the ability to give incorrect information would be great. For critical failures on recall knowledge checks, and failures on recall knowledge checks with the Dubious Knowledge feat.

**Comment by samgrieve** [comment]
That's the thing that I have always thought would be hard to achieve with a module like this. Ability to provide false info would be amazing.

**Comment by weepingminotaur** [comment]
Seconding the call for false info. Would be an amazing addition.

**Comment by WBHarry** [comment]
A first step has been taken. The newly released version 0.8.4 allows missinformation on the creature name. 🥷

**Comment by WBHarry** [comment]
I just released v.0.8.6 that added missinformation as a big feature. I close this issue, and present to you, The Coffee Monster! (trust me)
![image](https://github.com/user-attachments/assets/ab023c38-aa4e-4f10-bf50-b083f24fefe0)
