### ISSUE TITLE
Error generated trying to display the Command spell

### ISSUE THREAD

**Issue by farling42** [WBHarry/pf2e-bestiary-tracking#10]
An error is produced when trying to display the Command spell, which seems to be related to this module.

![image](https://github.com/user-attachments/assets/0f8b1907-1122-4f38-89c5-d9c58d07de32)

**Comment by farling42** [comment]
![image](https://github.com/user-attachments/assets/fbd813c2-5530-4bfc-bec9-f21e73f3bcfa)

**Comment by WBHarry** [comment]
This error is fixed in the latest version. So update and you're good to go.

That handlebar helper was indeed silly and overwrote something already existing. I've made sure they won't conflict with stuff again 😁
