### ISSUE TITLE
[bug] notes tab needs scroll for new recall knowledge sidebar

### ISSUE THREAD

**Issue by Iankid** [WBHarry/pf2e-bestiary-tracking#100]
I have 6 players, and the sidebar for the new recall knowledge is no displaying all said player before the bottom of the window.

**Comment by WBHarry** [comment]
I just released v1.0.5 that fixes this. 🤖 👍  
Removed the reset button aswell to improve text flow. The player name can instead be clicked to reset the Recall Knowledge Attempt tracker (alt-click to avoid confirmation popup.)
