### ISSUE TITLE
[Feature Request] Recall Knowledge DC counter

### ISSUE THREAD

**Issue by Iankid** [WBHarry/pf2e-bestiary-tracking#103]
according to GM core, the GM is encouraged to increase the DC of recall knowledge after every attempt.
To fulfill this, I'm wondering if a counter, similar in design to the Influence counter, could be added. Except it would display DC: +1, +2 and so on.

**Comment by WBHarry** [comment]
Hm. Doesn't the current Recall Knowledge Attempt tracking in the Notes tab enable this?
I'd imagine GMs might handle their DC increases differently, so just checking the number of attempts should make it simply to figure out.
![image](https://github.com/user-attachments/assets/b2b2f406-b272-496e-8f44-77c218be47a5)

**Comment by Iankid** [comment]
suppose you are sorta right. At least, 4 slots feels like it might be a small limit? not that most players will go to or above that often. but it could theoretically be reached.

**Comment by WBHarry** [comment]
That's no problem! When you click in the last box for a row, a new row automatically pops up. So it's infinite.

**Comment by WBHarry** [comment]
Considering this solved as is. Open to revisit it if there are other considerations 🤖
