### ISSUE TITLE
[Feature Request] Better integration options - keybinding, send to Bestiary quick link

### ISSUE THREAD

**Issue by apoapostolov** [WBHarry/pf2e-bestiary-tracking#11]
- Keybinding to open/close-if-opened Bestiary (i.e. B)
- Send to Bestiary option in the header of PCs (if Bestiary also handled adding PCs) and NPCs.

**Comment by WBHarry** [comment]
I just released v0.8.9.7. It adds keybindings to the same functions as the macros hav been. 🤖 👍 
![image](https://github.com/user-attachments/assets/fc2eff1c-6806-4707-83f3-f523262ee0c0)
