### ISSUE TITLE
[bug] NPC view toggle not working for players

### ISSUE THREAD

**Issue by Iankid** [WBHarry/pf2e-bestiary-tracking#112]
The NPC view toggle does not seem to be functioning for player users.

![image](https://github.com/user-attachments/assets/de029aec-a8e5-410b-aeb7-5551f155ed58)

**Comment by Iankid** [comment]
hold on, this may be limited to this one creature

**Comment by Iankid** [comment]
replicated the bug with the base creature. Buso Farmer. Turn them into an NPC

**Comment by Iankid** [comment]
alright found the issue. It happens if the NPC in question has an affiliation tag that has no been revealed to the players yet.

**Comment by WBHarry** [comment]
Ah, yup good catch, I wasn't filtering out hidden categories for players in an update function.
I've put in a fix for it 🤖 👍

**Comment by WBHarry** [comment]
I released v1.0.13 that fixes this
