### ISSUE TITLE
Breaks Some Right Click Menus in Actors SideBar

### ISSUE THREAD

**Issue by Nargath** [WBHarry/pf2e-bestiary-tracking#113]
Foundry 12 Build 331
PF2e 6.4.0
Bestiary Tracking 1.0.13
 
An odd one.
When the module is active on its own, I lose the ability to bring up the right click menu on NPC and Party Actors in the Actors SideBar.
It still works right clicking on Folders in the Actors sidebar, and works on PCs in the Party folder, and other types of actors in folders or at the root level are all right-clickable.

None of the other sidebars lose this function either, just NPCs and PCs in the Actors sidebar.

**Comment by WBHarry** [comment]
Hm, well I am doing things to modify the right-click menus in the Actors sidebar.
I just tested this out in a new world with Bestiary Tracking as the only mod though, and I'm not seeing these issues 🤔 
https://github.com/user-attachments/assets/79c1a5c3-51b6-4c53-9061-30cba9840fed

**Comment by WBHarry** [comment]
I'm assuming you're getting some kind of errors in the console?

**Comment by Nargath** [comment]
Yeah, just a simple one
![image](https://github.com/user-attachments/assets/3eba7200-0ca8-4456-af7d-3bb1fd6868a7)

**Comment by WBHarry** [comment]
Hm. Yup, unfortunately there was a point in module development where a bad issue cropped up. It's not something that was possible for me to fix by migration for the users it effected, sadly.

To get things up to speed and working properly again, you'll have to use the `Bestiary Reset` macro included with the module in the compendiums. It will clear out any existing data in the Bestiary, and set up the modern framework for the Bestiary Data. This does mean losing the bestiary entries already made, but there isn't really another option I'm afraid.
![image](https://github.com/user-attachments/assets/f61e1f0c-884f-4be8-bee6-97a33632f59c)

Dumb thing that happened before things got stable 😅

**Comment by Nargath** [comment]
Yup, that fixed the issue right up!

Its all good on the data loss, more than happy to take a few bumps in the road on this awesome module!
