### ISSUE TITLE
Open Bestiary as Macro

### ISSUE THREAD

**Issue by Artetsu** [WBHarry/pf2e-bestiary-tracking#116]
I am not sure why the macro is not working with Monk's Active Tile triggers, I have it run as a macro but it's not opening for some reason, maybe I am not implementing this correctly.

**Comment by WBHarry** [comment]
Hm. I know another user did this same thing.
It should just be a matter of making the trigger run: `game.modules.get('pf2e-bestiary-tracking').macros.openBestiary();`.

**Comment by WBHarry** [comment]
Any errors in the console?

**Comment by Artetsu** [comment]
I managed to get it working somehow, I deleted the graphic image I was using and replaced it and then viola, there were also no errors in the console before. Thanks for the help anyway!
