### ISSUE TITLE
[Bug] Conflict with Monk's Enhanced Journal

### ISSUE THREAD

**Issue by Crowguard** [WBHarry/pf2e-bestiary-tracking#117]
Crossposting from https://github.com/ironmonk88/monks-enhanced-journal/issues/721

Foundry 12.331
MEJ 12.01
PF2 BT 1.0.15

**Comment by WBHarry** [comment]
Hm. It doesn't look that way when I enable the enhanced journal mods, but then again I have no idea how this module works as is :sweat_smile:
![image](https://github.com/user-attachments/assets/7057dde2-beb8-478c-827e-98330b29076b)

**Comment by Crowguard** [comment]
![image](https://github.com/user-attachments/assets/2520a569-efaa-4d35-8940-27c3835774f9)
It should just be adding the additional types in their own section below the core journal types. Also, I realized the things being added to the types are journal folders, not the actual journals. Try creating a few folders to test.

**Comment by WBHarry** [comment]
I just released v1.1.2 that fixes this. 🤖 👍
