### ISSUE TITLE
Hide hidden text.

### ISSUE THREAD

**Issue by bsleys** [WBHarry/pf2e-bestiary-tracking#12]
if the npc/creature had dm only text hide it from the players.  IE
![Screenshot 2024-08-13 220221](https://github.com/user-attachments/assets/2ee2558b-a2ad-4de1-ba5e-811b3e4802a4)

The above SS shows the players view when the Ability with constrict is show to the players.  The DC 19 should be hidden from the players and only the Basic Fortitude potion shown.  This is how it works when displayed in chat messages when used. 

Note the HTML for the element is 

`<span data-visibility="gm">DC 19</span>  `

So hide those gm only elements.

Thanks otherwise so far I'm loving the idea of the mod and am looking forward to using it in my games.

**Comment by WBHarry** [comment]
I was doing htmlEnrichment in the wrong place, so everyone was getting the GM view, so to speak.
This should be fixed in v0.8.6 version that I just released. :grin:
