### ISSUE TITLE
Cannot access right-click menus on chat cards

### ISSUE THREAD

**Issue by mgoldstein322** [WBHarry/pf2e-bestiary-tracking#123]
![image](https://github.com/user-attachments/assets/1b1c5272-50f1-46e1-a569-2ae607da708e)

I've been having an issue with not being able to right click on chat cards for the last day or so. Decided to run FtC and it settled on this one. I really like this module, so I figured I would let you know. 

![image](https://github.com/user-attachments/assets/fded6319-8e79-4c53-955c-a0829a60fc0a)

This is the error that pops up in the console when I go to right click on any of the chat cards.

I'm on the newest version of PF2e, Foundry, and this module.

**Comment by WBHarry** [comment]
Hm. I'm not able to replicate the issue. I'm not having any issues right-clicking on chat cards. 😕 

The error is essentially saying that you have some BestiaryEntry in your Bestiary that isn't a Bestiary type at all since it doesn't have a method defined.

Have you tried to disable other modules to see if it works standalone?

**Comment by WBHarry** [comment]
I went ahead and release v1.1.7. It adds import/export functionality for the whole Bestiary.

If you update to that version and export your active Bestiary in that world, then you can just upload the JSON file that ends up in your download folder here so I can import the Bestiary and check the error 😺 
![image](https://github.com/user-attachments/assets/a3dbc209-841b-4534-982f-f62a18b84b85)

**Comment by mgoldstein322** [comment]
Here you are my friend: 
[bestiary.json](https://github.com/user-attachments/files/17235064/bestiary.json)

Possibly related to these issues I'm having: when you released the update that made it so that the bestiary had a new category for the current combat encounter, it became impossible for the bestiary to open during an encounter for both me and my players. If I tried to open it at all, it would do nothing, but then immediately open when I end the encounter. The error that occurs in that case is posted below.
![image](https://github.com/user-attachments/assets/fe872b90-7d30-4519-b86e-4125ea587b3c)

**Comment by WBHarry** [comment]
Heya. I've found the issue.
![image](https://github.com/user-attachments/assets/5bbf40b4-40e5-448c-bee5-346a6956985e)

The module makes use of a hidden folder with a journal for data storage.
Every creature/npc/hazard is stored in this journal and read as data.

Somehow you've ended up with a lot of entries in that journal that are not made by this module, like these two:
![image](https://github.com/user-attachments/assets/318e7595-6c3a-4270-a933-d31e2aeb3f2d)
![image](https://github.com/user-attachments/assets/0a5ec1e2-aeeb-48bb-b685-7e43461b5ce5)

If you recognise these, are they entries you're writing yourself, or are they coming from some module, the Kingmaker campaign itself? 🤔

**Comment by mgoldstein322** [comment]
Yes, before your module released I was using his to make a pseudo-bestiary. I can delete all of them on my end since I don't need them anymore. I guess I can close this for now!
