### ISSUE TITLE
Feature Request: Add "Either Unique or NPC" Criterion

### ISSUE THREAD

**Issue by Armandeus66** [WBHarry/pf2e-bestiary-tracking#124]
Currently, we can choose to add an actor to the NPC pages based on whether it has unique rarity OR the NPC tag, not one or the other. Either all NPCs must have the NPC tag, or they all must be unique. You can't include both NPC-tagged and unique actors with one setting.
There are some instances (in the Fists of the Ruby Phoenix AP, for example) where actors with the same, non-unique actor sheet are used for NPCs, but aren't named, so they aren't "unique." In this AP, there is a group called the "enforcers," and aside from a couple of unique characters, most of them are based on the same few actors. However, from the players' point of view, if they were all under the "enforcer" faction in the NPC Gallery, it would be easier to understand than if the generic ones were in with the creatures.
Since you can only choose either the NPC tag or the unique rarity to have an actor show in the NPC Character gallery, I have had to make some adjustments to a bunch of actor sheets, but if we had a third option of "either NPC tag or unique rarity" that might be most useful in some cases.
Thanks for your consideration and hard work on this great module.

**Comment by WBHarry** [comment]
I just released v1.1.8 and I included this third option. Hope it works well for you 🤖 ✌️ 
![image](https://github.com/user-attachments/assets/b5c99043-098f-4393-9000-05926a1d1dbd)

**Comment by Armandeus66** [comment]
Thank you!
