### ISSUE TITLE
Avatar Menu sometimes gets toggled to revealed with new updates

### ISSUE THREAD

**Issue by Iankid** [WBHarry/pf2e-bestiary-tracking#129]
Every once in a while, when a new update comes out, I have to go through the bestiary for any NPCs I've hidden to art for, cause I've been finding them suddenly revealed.

**Comment by WBHarry** [comment]
Hm. Curious. I haven't noticed this, but then again I haven't actually been using the feature too much in my games so far.

I'll see if I can spot something weird in the code. 🤔

**Comment by Iankid** [comment]
Hmmm. Doesn't seem to be limited to module update causing it. I couldn't repeat it, but had it happen with an NPC I added background text for. I left, the server auto shutdown (Forge), and when I logged back in, their art was revealed.
attempted to repeat this process (with the only difference being a manual shutdown), but it remained hidden. So not sure what caused it.

**Comment by WBHarry** [comment]
I might have solved the issue. 

I released v1.1.12. I noticed that if you refresh a Bestiary Entry, then some auxilliary data such as the AvatarImageState got lost. Now the setting, such as 'outline' gets retained.

**Comment by WBHarry** [comment]
Considering this issue resolved. If the issue pops up again, feel free to open a new issue 😸
