### ISSUE TITLE
Bug: monster not added to bestiary when added from combat tracker

### ISSUE THREAD

**Issue by roi007leaf** [WBHarry/pf2e-bestiary-tracking#13]
When trying to add a monster to the bestiary from the combat tracker it looks like some data is missing and an error is thrown, maybe catch that use case and show a notification to tell that this operation is not supported :)

EDIT: it also looks like addMonster doesn't filter when a character actor is attempting to be added to the bestiary

**Comment by WBHarry** [comment]
Fixed this in v0.8.5. 
- There should now show up some proper errors if unintended things are dragged into the Bestiary. 
- Combat Registration now doesn't try to add things that can't be added to the bestiary 🤪
