### ISSUE TITLE
[Feature request] display shown info field in bestiary

### ISSUE THREAD

**Issue by Iankid** [WBHarry/pf2e-bestiary-tracking#135]
Not sure what this info field is labeled. But it usually contains basic labeling for the creature. It's useful for this to be in the bestiary as a reveal-able field, as using this sheet as an example, the actor is the creature's name, rather then what he is.

![image](https://github.com/user-attachments/assets/12d1a035-4679-4d27-8457-27fb433e6fba)

**Comment by WBHarry** [comment]
I released v 1.1.20. This field (technically called `blurb` but I refer to it as Name Info) will now have it's info added when you add/update a creature, and if the field is present it will be revealable by the GM.
I didn't do a migration, but basically it works for any changes from now on 🤖 👍
