### ISSUE TITLE
[Feature Request] Add Folder to Bestiary

### ISSUE THREAD

**Issue by Crowguard** [WBHarry/pf2e-bestiary-tracking#138]
Either the ability to drag & drop a folder in, or a right-click option to add all actors in that folder (and possibly sub-folders, but I know Foundry makes that tricky) to the bestiary.

**Comment by WBHarry** [comment]
Released v 1.1.20 that adds this functionality. 🤖 ✌️ 
You can either drag and drop a folder or rightclick the folder and select the `To Bestiary` option.
