### ISSUE TITLE
[enhancement] on screen refresh notification.

### ISSUE THREAD

**Issue by Iankid** [WBHarry/pf2e-bestiary-tracking#143]
Just for know that it's working and then finished, an on screen notification that the bestiary is refreshing, and then done refreshing, would be nice to have.

**Comment by WBHarry** [comment]
That's definately fair, I've thought about more notifcations in a few places but never gotten around to it.

**Comment by WBHarry** [comment]
I released v 1.1.23 with a few fixes to things. There are now notification messages for when you do a Bestiary Refresh. 🤖 👍 
![image](https://github.com/user-attachments/assets/5a319d8e-bad3-4225-9be6-37c055c728cc)
