### ISSUE TITLE
[feature request] Toggle reveal lock

### ISSUE THREAD

**Issue by Iankid** [WBHarry/pf2e-bestiary-tracking#145]
Thankfully I've yet to experience this. But I am realizing just how easy a GM could accidentally reveal spoiler information on the bestiary sheets. (particularly on NPCs).
Perhaps a lock setting would be useful, so the GM can be more rest assured that they won't accidentally reveal info, while browsing the bestiary menus.

**Comment by WBHarry** [comment]
Could definately be done, but is it really such an easy thing to do to accidentially reveal something?
There isn't really a reason to be clicking anywhere close to the revealable fields if you're not interested in revealing things, is there?

The closest thing I can think of would be while in EditMode on NPC sheets, but even then the edit field and the toggle isn't exactly adjacent. 🤔 
If any thing, I could imagine just making things not toggle:able while in edit mode.

**Comment by Iankid** [comment]
You may be right. as I said, I've yet to experience this myself. Just the passing fear. So if it needs to be tabled for now, I wouldn't object.
