### ISSUE TITLE
(Bug) Unable to Sort NPC Category Tabs

### ISSUE THREAD

**Issue by RandallCarter8100** [WBHarry/pf2e-bestiary-tracking#146]
I am suddenly unable to sort NPC Category Tabs.  I can usually grab one tab and drag to the desired spot.  However, now it just snaps back to its current position.   Been this way at least since last update a few days ago. 

(Ideally, a desired feature would be to have the option to set the Categories to auto-sort alphabetically upon creation - they do not right now, which is why I try to move them into such an order.)

**Comment by WBHarry** [comment]
I just released v1.1.24. It includes a bugfix for this, and also includes a dropdown select where you can choose to let NPC Categories be automatically sorted alphabetically 🤖 ✌️ 
![image](https://github.com/user-attachments/assets/98b6749d-eb43-4144-996c-954e9c3d9ac4)

**Comment by RandallCarter8100** [comment]
Thank you!!!
