### ISSUE TITLE
Expose the descriptiors (Low, High, Average, Very High) and allow to add custom Descriptors for extreme outliers (Impossibly High)

### ISSUE THREAD

**Issue by apoapostolov** [WBHarry/pf2e-bestiary-tracking#15]
As in title. Similar to Health Estimage, expose the values and strings used in the Settings and allow adding extreme (often will be funny ones to scare off players) descriptors for extreme outliers ("Don't even try!")

**Comment by weepingminotaur** [comment]
Seconding this request.

**Comment by WBHarry** [comment]
I just released v.0.8.7. It adds a new module settings menu, Bestiary Labels. It now exposes these settings so they can be customised. 😄 
![image](https://github.com/user-attachments/assets/792f034d-6588-461b-9e14-5aa2e6b71cea)

**Comment by apoapostolov** [comment]
Thank you!!
