### ISSUE TITLE
updateChatMessage hook callback throws an error when no flags are provided

### ISSUE THREAD

**Issue by Cuingamehtar** [WBHarry/pf2e-bestiary-tracking#151]
When no flags are provided on message update,
https://github.com/WBHarry/pf2e-bestiary-tracking/blob/2db882306d2b10d0ba6adbab9f0ee22ac91c2b51/BestiaryTracking.js#L18671
errors.

Suggest replacing with 
`const appliedDamage = flags?.["pf2e-toolbelt"]?.targetHelper?.applied;`

**Comment by WBHarry** [comment]
Was pretty sure flags was always provided as an object, wether empty or not.
I guess that might not always be true then

**Comment by WBHarry** [comment]
Added in this as a safety bit of code in v 1.1.28
