### ISSUE TITLE
[Bug] Unable to edit notes due to missing Permission error

### ISSUE THREAD

**Issue by Ribuska** [WBHarry/pf2e-bestiary-tracking#152]
Players cannot edit _some_ of the notes in the NPC Gallery's Character Sheet due to lack of Permission to edit the Journal entry, but the Permission is there. (Only Characters in NPC Gallery are affected.)
Strangely only some of the Characters are affected and even deleting and creating NPC cannot fix the issue. Also, some of the existing Character Sheets can become uneditable, with no sign or tell how.

Here's the only error in the console:
```
User Fishy lacks permission to update JournalEntryPage [Hdom7aLxCdHbTfor] in parent JournalEntry [OTxHX0jwjvBoTMLS]
Error: User Рыбуська lacks permission to update JournalEntryPage [Hdom7aLxCdHbTfor] in parent JournalEntry [OTxHX0jwjvBoTMLS]
    at /C:/My%20big%20shit/foundryvtt/Foundry%20Virtual%20Tabletop/resources/app/dist/database/backend/server-backend.mjs:1:5101
    at async Promise.all (index 0)
    at async ServerDatabaseBackend._updateDocuments (/C:/My%20big%20shit/foundryvtt/Foundry%20Virtual%20Tabletop/resources/app/dist/database/backend/server-backend.mjs:1:4748)
    at async Semaphore._try (/C:/My%20big%20shit/foundryvtt/Foundry%20Virtual%20Tabletop/resources/app/common/utils/semaphore.mjs:101:17)
```

Foundry v12.331
PF2E v6.7.0
PF2E BTv1.1.27

**Comment by WBHarry** [comment]
Hm, interesting.
Think you can export and send over the Bestiary that has the permission fails so I can easily find the error? 🤖 
![image](https://github.com/user-attachments/assets/9f72deda-dd08-48ac-9509-6e0824ee11f1)

**Comment by Ribuska** [comment]
So, our world has two bestiaries. Here's both of them.
[bestiariy-isekaya.json](https://github.com/user-attachments/files/17869872/bestiariy-isekaya.json)
This is the problematic one. Sorry, the text is in russian, but the code is there. There are some modules, but they shouldn't affect Journals at all.

And here's the second one, just in case.
[bestiariy-reshal.json](https://github.com/user-attachments/files/17869871/bestiariy-reshal.json)

**Comment by WBHarry** [comment]
Hm. Well, if you are getting permission issues, then the modules hidden data journal -must- not have permissions set for the players.
The module does set this up, so the only thing I could hazard a guess at is that some other module or macro you've been using has sweepingly changed journals.

-------
You can try copying and pasting this little bit of code in the console and see if it fixes it. It will set all players to the needed permissions on all Bestiary data journals. 🤖 
```
game.journal.filter(x => x.pages.some(x => [
    "pf2e-bestiary-tracking.creature",
    "pf2e-bestiary-tracking.npc",
    "pf2e-bestiary-tracking.hazard",
  ].includes(x.type))).forEach(journal => journal.update({ "ownership": { default: 3 } }))
```

**Comment by Ribuska** [comment]
Thanks! That really helped. And we think you're right, it might be some other module that changed the Permissions. Sadly, there's no way to know for sure which module did this as we have 182 modules (Only 83 of them are active, but all of them were aswell at some point).
I wonder if some sort of check or code is needed to prevent this error from happening in the future, but oh well. Thanks again!

**Comment by WBHarry** [comment]
I might toss in a check for it. It's just silly business with stuff changing mine willy-nilly. But but,
Glad it worked out :grin:
