### ISSUE TITLE
Unable to reveal information

### ISSUE THREAD

**Issue by SuspiciouslyStickySock** [WBHarry/pf2e-bestiary-tracking#17]
I as GM added a creature from the AP we are playing and as i tried to reveal the information (make it green) i was unable to do so with any information?

Video (May contain spoilers to AV so be warned)
https://youtu.be/RvXUr1yWtRA

**Comment by fishrobe** [comment]
I am in no way attached to this module but when that happened to me a few times reloading my browser fixed it. It's not ideal because it slows things down, but it's a work around before it's fixed anyway (hopefully it will work for you too).

**Comment by WBHarry** [comment]
This was an issue where creature that appear in more than one bookmark in the Bestiary could sometimes fail to toggle information.
This should be fixed in the newly released v0.8.6 :grin:
