### ISSUE TITLE
Search does not work

### ISSUE THREAD

**Issue by ThomaSutra** [WBHarry/pf2e-bestiary-tracking#19]
I was working with the Mod today in preparation for a game and after adding a dozen undead, I went to customize each entry.

I could not access the entries below the top 6. No way to scroll down to entries below or pop out the page. 

Tried to do a search in the undead section, and it tells me no undead were added. 

Need a fix to see bottom of page and search the page.

**Comment by WBHarry** [comment]
I just released v.0.8.6. Scrolling should work without issues now, and I fixed the silly way searching ended up working.

Hope game prep goes well :grin:
