### ISSUE TITLE
[BUG] Open Bestiary macro opens duplicates of the bestiary tracker

### ISSUE THREAD

**Issue by Mathiam17** [WBHarry/pf2e-bestiary-tracking#21]
The Open Bestiary macro `game.modules.get('pf2e-bestiary-tracking').macros.openBestiary();` opens a new bestiary window every time the macro is called. The macro should be a "toggle" and not a "open" macro.

**Comment by WBHarry** [comment]
A unique Application shouldn't actually be possible to open more than once.
The issue was that I'd forgotten to supply an ID for the Bestiary Application.

It's now fixed in 0.8.6 :grin:
