### ISSUE TITLE
Need to be able to turn on/off parts of resistances

### ISSUE THREAD

**Issue by ThomaSutra** [WBHarry/pf2e-bestiary-tracking#22]
Example, Wood Golem:

Resistant to all physical except Adamantine. The characters have learned the resistance but have not used adamantine yet, so do not know about it.

Can you create a way to show the resistances but not the exceptions until they find them out?

**Comment by WBHarry** [comment]
I sure can..could....well I did. I just released v0.8.9.3 that adds a new module setting under the `Bestiary Appearance` submenu: `(IWR) Exceptions And Double`. It allows you to toggle individual Exceptions and DoubleVs of weaknesses and resistances. 🥳 

https://github.com/user-attachments/assets/63ddcd15-221e-4ce7-a299-92f7190a2ff0
