### ISSUE TITLE
Resistances section glitch

### ISSUE THREAD

**Issue by ThomaSutra** [WBHarry/pf2e-bestiary-tracking#23]
Sometimes (ghosts for an example) the resistances block will not revel itself. Rather, there is a small dot under the block that will turn green when clicked, but still does not reveal information to players. 

Thanks,

You are doing a great Job!

**Comment by WBHarry** [comment]
Thanks! I'm happy with the way the module is turning out 😄 

About this issue,
Could you test this in a new world, on the latest version of the module, or alternatively just drag in the offending ghost to refresh it in the Bestiary with the latest version of the module installed? 

I did fix a bug regarding this in v0.8.6, and I can't currently replicated what you're experiencing.
![image](https://github.com/user-attachments/assets/68c6d0bb-18fd-4541-96a6-b87523dcc189)
Specifically there was previously an issue when wordy resistances had dots in them that I fixed.

**Comment by ThomaSutra** [comment]
Yes, it is fixed. Sorry it took me a while to get back to you.
