### ISSUE TITLE
Spells Known

### ISSUE THREAD

**Issue by ThomaSutra** [WBHarry/pf2e-bestiary-tracking#24]
A section wherein we can toggle the spells used by a creature

**Comment by WBHarry** [comment]
I just released v0.8.7. It adds a Spells tab where spell traditions, their spells and the Spell DC and Spell Attack Modifier can be revealed to players.
![image](https://github.com/user-attachments/assets/56a0fdc8-5043-47b2-9814-640aa03cc52a)
