### ISSUE TITLE
[Enhancement] Ability to reveal or hide sections with one click

### ISSUE THREAD

**Issue by weepingminotaur** [WBHarry/pf2e-bestiary-tracking#25]
If I want to make all actions viewable to players, it would be great to have a button to toggle that reveal state on or off for all actions. Similar with IWR, passives, attacks, and (eventually) spells.

**Comment by WBHarry** [comment]
I just released v0.8.9.3 that adds this as a feature. You can toggle all 'categories' on the Statistics tab such as Resistances, Actions, Attacks etc by clicking on the name of the section.
Spells I didn't actually think about for some reason. I'll keep this issue up and add that in an upcoming version.

**Comment by WBHarry** [comment]
I went ahead and quietely released v0.8.9.4 that added the ability to click on spell levels aswell to reveal/hide all spells under that level. Considering this closed with that 😁 👍
