### ISSUE TITLE
[Enhancement] Ability to set custom colours for hidden, revealed, and misinformation

### ISSUE THREAD

**Issue by weepingminotaur** [WBHarry/pf2e-bestiary-tracking#26]
Being able to control colour for info revealed state would be amazing.

**Comment by WBHarry** [comment]
Forgot to comment on this issue.

In uh..one of the latest versions I added `Contrast Reveal State` under the `Bestiary Appearances` menu in module settings.
Enabling it returns the colouring of Revealed/Hidden fields fo the GM. The colours can also be set. 

Misinformation isn't really coloured at the moment, instead it gets the little 'grammar-error' squiggles underneath.
![image](https://github.com/user-attachments/assets/f51e72a4-3f0a-40aa-92be-401f97d3b8f4)

**Comment by WBHarry** [comment]
Considering this closed for now. Possibly revisiting some further visual distinction for Misinformation at a later time.
