### ISSUE TITLE
[Enhancement] Ability to show / hide / misinfo creature level

### ISSUE THREAD

**Issue by weepingminotaur** [WBHarry/pf2e-bestiary-tracking#27]
I typically reveal creature level to players when they first RK a monster. Being able to misinfo them on creature level (if they crit fail) would be very amusing. :D

**Comment by WBHarry** [comment]
I just released v0.8.7.1. It adds the module setting `Show Monster Level`. Enabling this adds a monster's level to the creature view so it can be revealed with or without misinformation. 😄

**Comment by weepingminotaur** [comment]
Thank you so much!
