### ISSUE TITLE
[Enhancement] Ability to show/hide languages

### ISSUE THREAD

**Issue by bsleys** [WBHarry/pf2e-bestiary-tracking#28]
As the title says show/hide creature languages.  Should be able to show them individually.  Useful for social skills that require specific languages.

On another note. loving this as did my players last night.

**Comment by WBHarry** [comment]
Forgot to update this issue.
Languages are in as an optional field in one of the recent updates. Just have to enable it in the Module Setting 🥳 
![image](https://github.com/user-attachments/assets/80c07d72-163b-41de-8eb1-9ee7d9d0e4ef)
