### ISSUE TITLE
[Feature Request] Ability to filter by less common monster traits

### ISSUE THREAD

**Issue by piper93** [WBHarry/pf2e-bestiary-tracking#29]
I'm loving the bestiary tracker so far! I was just wondering if it would be possible to do something so that if a creature is added with a trait not currently in the sidebar, it would add that trait. For example, I'm using it in my Season of Ghosts campaign and several of the monsters have only the Kami trait, which means they aren't visible in the bestiary.

**Comment by WBHarry** [comment]
Ah, I forgot to update this issue.
I released v0.8.9 yesterday. It  introduces this feature. 😁 🎉 
![image](https://github.com/user-attachments/assets/b4e34fdb-cc37-47bb-a09f-9f5bdbc508cf)

**Comment by WBHarry** [comment]
Also, creatures that lack any traits in the bookmarks will appear in the 'Unknown' category now. If you later add some trait they have to the `Additional Creature Types` setting, they'll be resorted.
