### ISSUE TITLE
Suggestion: Player notes

### ISSUE THREAD

**Issue by xdy** [WBHarry/pf2e-bestiary-tracking#3]
A text field on each creature that players can edit would be useful. And possibly amusing for the GM to read the players speculations. :)
Saved in a flag perhaps? Or a journal with a page per monster?

**Comment by apoapostolov** [comment]
I would love to see this as well, preferrably using a database flag rather than a journal.

**Comment by WBHarry** [comment]
I did some toying around with this, and what I'd ideally like to do is use the collaborative editor that foundry has since v12. It doesn't seem possible to do because of the nature of this application though, so I'm back to the drawing board.

**Comment by rmcleveland** [comment]
> A text field on each creature that players can edit would be useful. And possibly amusing for the GM to read the players speculations. :) Saved in a flag perhaps? Or a journal with a page per monster?

I just installed this and this was the first thing my players asked if it can do.

**Comment by WBHarry** [comment]
I do want to add this functionality. My issue is that if I can'd do it with collaborative editing for the players, then it'll be really weird, since it's an application everyone is in at the same time 🤔

**Comment by xdy** [comment]
Optimistic locking per creature perhaps? I.e. if you edit after someone else you lose your edits as the first edit is loaded over yours. Probably good enough.

**Comment by WBHarry** [comment]
Hm..experimented some with a system where only one player can have 'the pen' at a time.
The one really undersirable thing is that the Bestiary is a data structure only the GM can edit and save. I can let players save the notes by routing through the GM - but that means the GM has to be online for the players to be able to write notes, which is bad 😞

**Comment by WBHarry** [comment]
A lengthy discord discussion has led to a possible way forward though. We'll see! 😁

**Comment by WBHarry** [comment]
Ít's been a long journey, but Player Notes are finally in with the release of v0.8.9.9 to end of the 0.8 versions. Collaborative editing of players at the same time🥳 

![image](https://github.com/user-attachments/assets/54b50efa-989a-434f-9ae8-e49a21e7ba26)

**Comment by rmcleveland** [comment]
This is amazing!!! You are awesome!

**Comment by apoapostolov** [comment]
Thank you!
