### ISSUE TITLE
[Enhancement] Update bestiary from Compendia

### ISSUE THREAD

**Issue by haydenhayden011** [WBHarry/pf2e-bestiary-tracking#30]
A setting/thing that allows you to update everything in the player bestiary from stuff in your compendiums. I use a ton of homebrew creatures, that I haven't yet made lore for. It would be nice to be able to do a one click set all.

**Comment by WBHarry** [comment]
I've been meaning to add a 'Refresh' button on the creature view. But it's a good idea to also add a 'Refresh All' option. I'll be adding it to the Bestiary menu like so:
![image](https://github.com/user-attachments/assets/42d52040-3222-4b36-a6a1-4b6036380df6)

**Comment by WBHarry** [comment]
I just released v0.8.8 and it adds the mentioned button above. It will refresh the data of all the creatures in the compendia, but retain the revealed status of it (exception is Immunity/Weakness/Resistance, haven't been able to find a solution for those yet).
You can also just drag a creature that's already in the compendia to it again to refresh just that creature.
