### ISSUE TITLE
Creatures Show up in tabs that have traits not yet revealed to the party

### ISSUE THREAD

**Issue by haydenhayden011** [WBHarry/pf2e-bestiary-tracking#31]
I have a creature that is humanoid, but they don't know hes undead. He shows up as undead in the bestiary tracker for everyone to see

**Comment by WBHarry** [comment]
This is something that's been brought up, and something I'm definately going to fix.
The idea is that a creature at first would appear in an 'Unknown' bookmark. When they have Creature Type Traits unveiled, then they will instead appear in those bookmarks.

**Comment by WBHarry** [comment]
I just released v0.8.8 and this is a feature in it. Creatures will be placed into an 'Unknown' category if the GM hasn't revealed any of their Creature Type Traits.
