### ISSUE TITLE
Errors attempting to open bestiary

### ISSUE THREAD

**Issue by Sorellia** [WBHarry/pf2e-bestiary-tracking#32]
I attached the errors below; the first error occurs whenever I try to open the bestiary window (whether that be through a macro or the sidebar button) and occurs regardless of user attempting to do so.

The second error was when I tried to open the vague descriptions setting panel. My best guess is that this is some sort of failed migration? It was working yesterday evening before you added the new custom labels and whatnot in v0.8.7, and crucially this world has had the module installed since you released it.

Another world I tried it on worked no problem, but that world has never previously had this module installed, so all of the data was fresh, hence the thought that it might be migration-related?

![Capture](https://github.com/user-attachments/assets/beaf3880-3ef0-47fc-8ef9-d586c43cba17)

**Comment by WBHarry** [comment]
Interesting, I have a migration in place for that, but it must have failed for an old bestiary entry somehow.
To fix this you should be able to just create a macro on your hotbar. Set it to `type = script`. And add this as the macro
```js
const vagueDescriptions = game.settings.get('pf2e-bestiary-tracking', 'vague-descriptions');
await game.settings.set('pf2e-bestiary-tracking', 'vague-descriptions', {
   properties: {
        ac: vagueDescriptions.ac,
        hp: vagueDescriptions.hp,
        resistances: vagueDescriptions.resistances,
        weaknesses: vagueDescriptions.weaknesses,
        saves: vagueDescriptions.saves,
        perception: vagueDescriptions.perception,
        speed: vagueDescriptions.speed,
        attributes: vagueDescriptions.attributes,
   },
   settings: {
      playerBased: vagueDescriptions.playerBased,
      misinformationOptions: vagueDescriptions.misinformationOptions,
   }
})
```
Running it should do the migration that failed. Let me know how it goes 🤖

**Comment by Sorellia** [comment]
That did indeed do the trick, many thanks :D
