### ISSUE TITLE
[Bug?] Bestiary labels menu only has Misinformation labels (short and full)

### ISSUE THREAD

**Issue by weepingminotaur** [WBHarry/pf2e-bestiary-tracking#34]
It's possible I'm not understanding the menu. But since it is accessible by clicking Bestiary Labels from the module settings page, I assume that I'd get at least one section that lets me customize just the base vague labels without getting misinformation territory.

**Comment by weepingminotaur** [comment]
I think it may be just a mislabel issue. The values in the full category show up for players when it's not misinformation.

**Comment by WBHarry** [comment]
Ah, that's true. I guess I was thinking of it in terms of Misinformation since I was doing something with it at the time.
You're correct that it effects all vague descriptions.

So it should probably be called **Vague Descriptions** 😁

**Comment by WBHarry** [comment]
I just released v0.8.8 and it renames the section to *drumroll* Vague Descriptions!
