### ISSUE TITLE
[Enhancement] Macro to add selected token to bestiary (GM use only)

### ISSUE THREAD

**Issue by weepingminotaur** [WBHarry/pf2e-bestiary-tracking#35]
In combat, a quick way to get a monster in the bestiary would be to select the token (which the GM is probably already doing) and run a macro that adds it to the bestiary.

On a side note, I cannot thank you enough for this module, which is already amazing.

**Comment by WBHarry** [comment]
I just released v0.8.8 and it adds a macro for this: `Add Monster.`

**Comment by weepingminotaur** [comment]
Thank you!!
