### ISSUE TITLE
Openning Bestiary for new worlds not working.

### ISSUE THREAD

**Issue by Mermut** [WBHarry/pf2e-bestiary-tracking#37]
I've got a couple of campaigns ongoing.
Since the last update, my worlds that I'd already started populating the bestiary can still open the bestiary.
In worlds that did NOT have anything in the bestiary, I cannot open the bestiary via the button from the journal notes. Also the Open Bestiary macro is not showing up in the compendium.
In configure settings, I can open the vague description settings in worlds with a populated bestiary but NOT in worlds with an empty bestiary.

**Comment by WBHarry** [comment]
I just released v0.8.8 which should fix these problems. If you can update and verify I'd appreciate it 😄

**Comment by Mermut** [comment]
The macro is back, but none of the rest of the functionality for new worlds has changed.
Neither using the macro no clicking on the button in the journal note section of the foundry interface opens the bestiary for worlds with empty bestiaries. Similiarly, the vauge description settings in the configure settings for the module doesn't open for new worlds.

All of the old functions and the new ones DO work for worlds where I've got populated bestiaries.

**Comment by WBHarry** [comment]
Could you open up the console and run: `game.settings.get('pf2e-bestiary-tracking', 'version')` and post the version number here? I'm curious if the migration is stuck on an old number because of some error.

**Comment by Mermut** [comment]
![image](https://github.com/user-attachments/assets/8ca0286a-5411-4998-a650-3fa9b25522ea)

I'll check with a new world, the others are existing worlds (one is my testing world and the other is one where the party doesn't do many recall knowledge checks so I hadn't populated the bestiary when I activated the module originally)

**Comment by WBHarry** [comment]
Settings are definately remembered, but they shouldn't have to be cleaned out. Rather, it's a good thing they're there incase the module is enabled again.

The reason I was curious about `game.settings.get('pf2e-bestiary-tracking', 'version')` on failing worlds is because that will show how far the migration scripts managed to run - and that could be different than the module version if there are errors. IE, maybe it failed to migrated from 0.8.7.2 to 0.8.8

**Comment by WBHarry** [comment]
I've been trying to create old worlds and then migrating them up to current, but I can't seem to replicate these errors.

If you'd be able and willing to zip up one of your failing worlds, then I could have a look at these errors and see what's going wrong 🧐

**Comment by Mermut** [comment]
Whatever it was, the most recent update (0.8.8.2) is now working in the one remaining world that it wasn't working in.
I just loaded the module back into it and was going to see if I could get any error generation and it loaded up correctly.

I'm not sure what changed... but at least the bug seems to have been smooshed.

**Comment by WBHarry** [comment]
I just released v0.8.8.3 that should remove any further migration issues aswell. Glad you're enjoying the module 🫶
