### ISSUE TITLE
Red to Green color change is gone with the latest update

### ISSUE THREAD

**Issue by ThomaSutra** [WBHarry/pf2e-bestiary-tracking#41]
When I reveal a Stat, it used to go from red to green. Now it stays the same color, with a highlighted boarder. For those of us with Poor vision, the boarder is nearly impossible to see.

Please bring back the Red/Green or give us an option to choose.

**Comment by maplealmond** [comment]
Seconded.  Miss the old color scheme.  The purple is visually nice for players, but not very useful for a GM in a hurry.

**Comment by WBHarry** [comment]
I just released v0.8.8.2. It introduces a new menu, Bestiary Appearance. Inside there is a section for Contrast Revealed State. Enabling this returns different colours for Revealed/Hidden properties on a creature.

Oh, and the colours can also be customized 😎 
![image](https://github.com/user-attachments/assets/2a15d7ba-8ec1-4e80-adbf-6e1c2af8d5c3)
![image](https://github.com/user-attachments/assets/f2ea742d-3b05-4e48-8506-400263e1c284)
