### ISSUE TITLE
Suddenly cannot open Bestiary

### ISSUE THREAD

**Issue by ThomaSutra** [WBHarry/pf2e-bestiary-tracking#42]
Tried as a DM and as a Player. Can no longer open the Bestiary either by Hotbar Key or main access on side bar.

**Comment by Mermut** [comment]
> Tried as a DM and as a Player. Can no longer open the Bestiary either by Hotbar Key or main access on side bar.

Is the Bestiary empty? I ran into a similar issue between updates. After some testing it's related to old settings. I believe the mod dev is working on it.
In my testing I was able to 'fix' the issue, by removing the mod, then clearing out the settings directory in the world directory and then re-enabling the mod. If you take this route, you'll have to redo ALL your mod settings however.

**Comment by Crowguard** [comment]
Also running into this.

### Error upon loading in when running FTC

![chrome_rlW17oQul3](https://github.com/user-attachments/assets/9e40d3d0-f6b4-40bc-8ffe-df5d5ecd29f0)

### Error when clicking the bestiary button

![chrome_GhICcFyz8j](https://github.com/user-attachments/assets/6e38be8f-c4d4-4a57-8177-9b01ca395a74)


### Info

Foundry 12.330
Bestiary 0.8.8.1

**Comment by nicholasfoote** [comment]
Getting this as well. It just does not open, and other than the console, doesn't show any errors or notifications, just a silently does nothing with either the button of the macro.

Foundry 12.331
Bestiary 0.8.8.1

In Chrome and Edge, I get this in the console:

```
Uncaught (in promise) TypeError: undefined. Cannot read properties of undefined (reading 'values')
[Detected 1 package: pf2e-bestiary-tracking(0.8.8.1)]
    at bestiary.js:257:68
    at Array.reduce (<anonymous>)
    at PF2EBestiary.prepareBestiary (bestiary.js:252:52)
    at PF2EBestiary._prepareContext (bestiary.js:292:33)
    at async #render (foundry-esm.js:44319:23)
    at async Semaphore._try (foundry-esm.js:6645:19)
```

In Firefox I get this:

```
Uncaught (in promise) TypeError: monster.traits is undefined
[Detected 1 package: pf2e-bestiary-tracking(0.8.8.1)]
    monster https://foundry.mydomain.com/modules/pf2e-bestiary-tracking/module/bestiary.js:257
    prepareBestiary https://foundry.mydomain.com/modules/pf2e-bestiary-tracking/module/bestiary.js:252
    _prepareContext https://foundry.mydomain.com/modules/pf2e-bestiary-tracking/module/bestiary.js:292
    #render https://foundry.mydomain.com/scripts/foundry-esm.js:44319
    _try https://foundry.mydomain.com/scripts/foundry-esm.js:6645
    add https://foundry.mydomain.com/scripts/foundry-esm.js:6617
    add https://foundry.mydomain.com/scripts/foundry-esm.js:6615
    render https://foundry.mydomain.com/scripts/foundry-esm.js:44291
    onClick https://foundry.mydomain.com/modules/pf2e-bestiary-tracking/pf2e-bestiary-tracking.js:74
    _onClickTool https://foundry.mydomain.com/scripts/foundry.js:81660
    jQuery 2
bestiary.js:257:53
```

**It does work in Ripper93's Foundry client though**, which is built on Electron.
https://github.com/theripper93/fvtt-player-client

**Comment by WBHarry** [comment]
I've tried creating old worlds and migrating them  up to current, but I can't replicate these errors.

If any of you would be willing to zip up one of your failing worlds, then I can open it up and see the error and what is actually going wrong. 🧐

**Comment by WBHarry** [comment]
Alrighty. v0.8.8.3 is now out. It should fix these sorts of issues. Since this is a bit of a gathering of bugs that I believe came from the same thing, I will close this issue - and if something crops up feel free to open a new one! 🧑‍🔧
