### ISSUE TITLE
[Bug] When "Vague Details" is enabled for saves, the numbers are still visible

### ISSUE THREAD

**Issue by HydrallUrakan** [WBHarry/pf2e-bestiary-tracking#45]
I've set saves to have vague descriptions, but the numbers are still visible. Possibly a bug, given that if I try to set misinformation for them, it uses the proper Ex/Hi/Mod/Lo/Ter dropdown rather than a numeric field.

Module v0.8.8.2 (Edit: Still appears to be happening after I updated to v0.8.8.3)
PF2e v6.2.2
Foundry v12.331

![image](https://github.com/user-attachments/assets/663a10ba-c471-44ef-a06b-3f85f4ac7a0d)
![image](https://github.com/user-attachments/assets/963d2be0-6eef-43c7-8bfc-5468f8c49483)

**Comment by WBHarry** [comment]
Just leaving a note here that I've fixed this issue and it will be included in the next little release. I just want to bring out a few small features aswell 😄

**Comment by WBHarry** [comment]
I've just released v0.8.8.4. It fixes the vague saves again 😁
