### ISSUE TITLE
[BUG] Vagues saves setting show bugged information to players

### ISSUE THREAD

**Issue by Mermut** [WBHarry/pf2e-bestiary-tracking#46]
v 0.8.8.3
When vague saves are set, the word settings are now showing, just a reference to the table
![image](https://github.com/user-attachments/assets/8a371ff6-188f-476a-b135-bc15fbe4cd56)
I'm not sure if this is revlavent or not, but this is what's showing up on player side in the f12 window 
![image](https://github.com/user-attachments/assets/4366dd60-e41f-43d0-96dc-e2fd4f1f6c24)

**Comment by WBHarry** [comment]
If the translation strings are showing like that, then it's something that got left over from an old version. It's easy to fix though. Just go to the `Bestiary Labels` module settings menu and hit reset on the labels and save.

There is however another bug related to saves at the moment which I will soon push out a fix for.

**Comment by WBHarry** [comment]
I've just released v0.8.8.4. It has a fix to display saves properly. 🥳
