### ISSUE TITLE
Ability to toggle parts of a resistances, Specifically exceptions

### ISSUE THREAD

**Issue by ThomaSutra** [WBHarry/pf2e-bestiary-tracking#47]
Example:

Wood Golem

Resistances:
Physical 5 (except Adamantine)

I am running a game wherein the party fought a wood golem and learned it is resistant to physical, but never learned the Adamantine part.
Would be nice to be able to expose the resistance but not the exception

**Comment by WBHarry** [comment]
I just released v0.8.9.3 that adds this as an optional feature under the `Bestiary Appearance` submenu in module settings. 😁 

https://github.com/user-attachments/assets/51a18478-4d53-48b9-9669-4eeb151cd8c6
