### ISSUE TITLE
[Feature Request] Share Attack and Ability damage type and traits

### ISSUE THREAD

**Issue by Nargath** [WBHarry/pf2e-bestiary-tracking#49]
This makes for an awesome addition to Roll For Combat's monster parts system!
Would it be possible to add the ability to share the individual traits for Attacks and Abilities and damage types?

For example, be able to share that a moose's Antler attack is piercing damage, or that a Sky Dragon's Breath Weapon has both the Divine and Electricity traits?

I can see a massive use when it comes to PCs that like to prepare ahead of time (if required), and also the monster parts system requires monsters with specific types and traits be used for specific upgrades.

So being able to share only those details, without giving away the maths, feels like its way more immersive

**Comment by WBHarry** [comment]
I've just released v0.8.9.6. It adds an optional setting that allows you to toggle individual attack traits.
Partway there 😁 
![image](https://github.com/user-attachments/assets/3a52bae4-3038-49ee-bd16-132b62d0550c)

I'll be looking to expand with two more optional Detailed Information Toggles for `Action Traits` and `Damage Types`

**Comment by WBHarry** [comment]
I just released v.0.8.9.7 that adds Action Traits and Damage Types to the Detailed Information Toggles aswell.
![image](https://github.com/user-attachments/assets/380722b9-65d1-4f75-9bb7-deb60f971240)

Considering this issue resolved 🤖 👌
