### ISSUE TITLE
[Feature Request] Streamline monster sheet access

### ISSUE THREAD

**Issue by Mathiam17** [WBHarry/pf2e-bestiary-tracking#5]
Currently there are only two ways to access a monster sheet in the bestiary tracker:
1. Use the macro on a targeted token
2. Access via the journal notes sidebar (then find the monster in the list)

It'd speed up play and make it simpler for players to double-click a monster token to directly open it's respective monster sheet. As currently double-clicking (for players) on a live monster does nothing it's a great opportunity to add an intuitive way to access the information a DM wants to present.

On the GM side - add a button in the token right-click menu (don't know the official name for it), that opens that specific monster/token in the bestiary tracker.

Additionally it'd be great if a GM-only "Show Players" button could be implemented to quickly get the players on-track or draw attention to the sheet.

**Comment by weepingminotaur** [comment]
At minimum, there should be a macro to simply open the bestiary tracker that doesn't require targeting a creature.

**Comment by WBHarry** [comment]
The newly released v0.8.4 shifted to include a macro compendium. There is now a `Open Bestiary` macro included.
As for double clicking or something similar..I'll do some experimentation 🤔

**Comment by WBHarry** [comment]
@Mathiam17 I just released v.0.8.8. It adds a module setting called `Double Click Open`. It needs the LibWrapper module to work, but it adds double clicking on tokens to go to their Bestiary page. GMs need to hold the alt key when they do it, since otherwise they open the actual NPC sheet. 🥳
