### ISSUE TITLE
[Feature Request] Unlock Bestiary Entry Features from Action-Chat Messages

### ISSUE THREAD

**Issue by Neakas** [WBHarry/pf2e-bestiary-tracking#50]
Ok now i tried one Session with this Module and in Theory i like it alot. I would just need a little bit more easy of use for me to use it. Dont get me wrong its already great. IF im going to use it, im going to use it completly, so: While in Combat i would need to keep a sheet open for every Creature in the Fight and just when i use an Ability i would need to unlock that Ability for the Players, since they "just seen it". 

A right-click Menu Entry to "Unlock Ability in Bestiary" would be a Great Help. Otherwise i would need to Curate the Entries after Every fight and i am really forgetful, ("did the players saw this ability?") and i mostly did not find the Time in my first Session with this Module.

So if i could just Post the "Rend" Attack to Chat (i always post GM only. not public), then right-click -> Unlock Ability in Bestiary, and then i could set those Abilities to Vague in the Settings and im done. The Players then know that that Ability exists and if the "unlock" Bonus information on those Abilities i can give those to the Players.

Since i have someone in my Party that uses Recall Knowledge basicly once per Turn, i would really like to use this Module a lot.

**Comment by WBHarry** [comment]
That sounds like a great thing. I'll definately look into it. 😎

**Comment by WBHarry** [comment]
I just released v0.8.9.5. It doesn't add a right click option on messages, but it does add automated revealing. 🥳 
![image](https://github.com/user-attachments/assets/eb44f91a-fb7c-4886-b445-405d5e02bc88)
Selecting these options makes using abilities/skills etc automatically revealed them on creatures in the Bestiary.

Unsure if this fully closes this issue as I might still add a manual option for those that don't want the automatic

**Comment by Neakas** [comment]
this is already fantastic! Thank you a lot! i wouldnt say no to the the Right-Click.> reveal, if you might implement it, so if you want to keep this issue open, to keep an eye on it, go ahead :)

**Comment by Neakas** [comment]
ill play around with the new feature in the coming week! if i find any issues ill let you know! have a great weekend!

**Comment by WBHarry** [comment]
I just released v0.8.9.8. It adds a reveal button to chat messages for abilities/attacks/spells/saving-throws/skills, if you don't want to use automatic revealing. 🥳 
![image](https://github.com/user-attachments/assets/7efe0a0b-5354-4618-aae1-72925bbdf945)
