### ISSUE TITLE
Names became obscured with new patch

### ISSUE THREAD

**Issue by ThomaSutra** [WBHarry/pf2e-bestiary-tracking#53]
After the latest patch(s), All the names of my entries went from revealed back to hidden.

**Comment by WBHarry** [comment]
Oouf, yeah I can see now that I misspelled 'revealed' as 'revaeled' in one place in the migration, making that happen.
I'll put in a fix for those that haven't updated yet, but I can't really get those statuses back I'm afraid.

Thanks for pointing it out 🫡

**Comment by ThomaSutra** [comment]
I am glad to be of help in this project!
