### ISSUE TITLE
[Enhancement] Hazard support

### ISSUE THREAD

**Issue by weepingminotaur** [WBHarry/pf2e-bestiary-tracking#54]
I realize this is a big feature, but it is a logical one, given what the bestiary does. Hazard support would be awesome.

**Comment by WBHarry** [comment]
It's definately something I've been thinking about. Right now I'm thinking of doing it something like this, to switch between the different sections of the Bestiary.
![image](https://github.com/user-attachments/assets/03bc4c23-18e5-4ec4-8008-d8c4f59d6100)

**Comment by WBHarry** [comment]
![image](https://github.com/user-attachments/assets/98daedc9-bad3-4edf-9667-f1b89d3ac78d)
A little tease never hurt 🚀

**Comment by WBHarry** [comment]
Oh, yup. This was the milestone for version 1.0.0 that released today. Closing this one up 🥳 ✌️
