### ISSUE TITLE
Parenthesis and Commas after entries

### ISSUE THREAD

**Issue by ThomaSutra** [WBHarry/pf2e-bestiary-tracking#56]
Not causing any issues, but I noticed that many stat entries now have a set of Parenthesis and commas after them:

( )
(, )
(, , , )

These are after the attacks, abilities and passives

**Comment by WBHarry** [comment]
Hm. I guess the migration wasn't smooth on that. You can easily fix that by updating the bestiary via the context menu, or by dragging in the creature again. 
The commas are the attack/abilities/passives failing to show their traits 😅 

I'll whip up a fix to make sure they migrate though. Thanks for reporting it.

**Comment by WBHarry** [comment]
I released v0.8.9.8.1. It should fix so that the traits are properly displayed. 👍
