### ISSUE TITLE
BUG: Journal Right-Click Context Menu Gets Disabled

### ISSUE THREAD

**Issue by Armandeus66** [WBHarry/pf2e-bestiary-tracking#57]
With the latest version of this module runniing, right-clicking a journal on the right-hand side journal list no longer shows the context menu, and gives this error.

BestiaryTracking.js:5691  Uncaught TypeError: Cannot read properties of undefined (reading 'type')
[Detected 1 package: pf2e-bestiary-tracking(0.8.9.8.1)]
    at Object.condition (BestiaryTracking.js:5691:22)
    at ContextMenu.render (foundry.js:68543:67)
    at HTMLElement.<anonymous> (foundry.js:68464:19)

Edge and Chrome, Foundry 12.331, PF2E 6.2.3, PF2E Bestiary Tracking 0.8.9.8.1

**Comment by WBHarry** [comment]
Thanks for reporting it. I pushed out v.0.8.9.8.2 just now to fix it. 🤖 👍
