### ISSUE TITLE
Cannot Open Bestiary

### ISSUE THREAD

**Issue by mgoldstein322** [WBHarry/pf2e-bestiary-tracking#58]
Simple as the title says. I can't open the Bestiary as GM via the macro or keybind, and the button in the actors tab does nothing. I'm not sure if the button being gone from the left side menu is intentional or not, but it doesn't show there either.

I'm using Foundry 12.331, PF2e 6.2.3, and your module at 0.8.9.8.3. I have used the Find the Culprit, and it continues to not work when there are no other modules active.

**Comment by mgoldstein322** [comment]
I suppose I can reset it after I put all my creatures in it :') haha

I suppose I should have expected this since it's not in 1.0 yet. The reset macro did not fix it, though.

**Comment by WBHarry** [comment]
Sorry. I did make a big data shift at some point to be able to do work much better and safer going forward, but here have been issues with getting old data migrated.

It's worth updating to v.0.8.12 I just pushed out as it fixes some bugs. It probably doesn't resolve this though, so in that case:

--
I have a more thorough macro you can run that should definately clean things up for you. Just need it on the hotbar as a script type and run it once.

```js
await game.journal.getName('pf2e-bestiary-tracking-journal-entry')?.delete();
await game.folders.getName('pf2e-bestiary-tracking-folder')?.delete();

await game.settings.set('pf2e-bestiary-tracking', 'bestiary-tracking', {
        monster: {},
        npc: {},
        metadata: {
            version: '0.8.11'
   }
});

const folder = await Folder.create(
{ 
   "name": 'pf2e-bestiary-tracking-folder', 
   "type": "JournalEntry" 
});
        
const journal = await JournalEntry.create({
            name: 'pf2e-bestiary-tracking-journal-entry',
            pages: [],
            folder: folder.id
});
    
await journal.update({ "ownership.default": 3 });
```

**Comment by mgoldstein322** [comment]
Don't worry about it! That script worked to fix it, thank you!
