### ISSUE TITLE
Make monster lore available

### ISSUE THREAD

**Issue by weepingminotaur** [WBHarry/pf2e-bestiary-tracking#6]
The ability to hide or reveal the description text that typically appears on the Notes tab for a given monster.

**Comment by weepingminotaur** [comment]
Just a note: thank you so much for making this module! Going to be extremely useful at my Pathfinder table.

**Comment by apoapostolov** [comment]
Thanks from me as well. I would also like to add that when revealing the description, allow to reveal the description and the privaste notes. The private notes as an additional field is the best place to add a abridged version of the mosnter AI in a storyteller tone (i.e. like described by an actual adventurer) via AI, or a translation in my local language. This allows me to not edit the core description of a monster that may contain too much or too generic lore, but be able to show a player-facing one.

**Comment by WBHarry** [comment]
I just released v0.8.6 and the public and private notes that appear in an NPCs `Notes` section are now available to be toggled under the Lore tab in the bestiary.
![image](https://github.com/user-attachments/assets/ec73e896-8769-4825-8e89-ff5924f2e539)
