### ISSUE TITLE
[BUG] Error when no actor for message

### ISSUE THREAD

**Issue by ChasarooniZ** [WBHarry/pf2e-bestiary-tracking#60]
![image](https://github.com/user-attachments/assets/8c2335c5-b90f-45b1-8407-6f743ff6ffa5)
![image](https://github.com/user-attachments/assets/3a275ec1-f40f-4963-a7a2-a244ac00b3b7)

_happened when i rolled persistent damage from a journal_

**Comment by WBHarry** [comment]
Huh. That's interesting. I'm curious how that option is even available in the right-click menu from something like that.
Thanks for reporting it, going to take a look 🧑‍🔧

**Comment by WBHarry** [comment]
Silly oversight on my part. I pushed out v0.8.9.9.4 that fixes this, aswell as another important bug that was making new worlds not setup correctly. 🤖

**Comment by ChasarooniZ** [comment]
💖
