### ISSUE TITLE
Update issue?

### ISSUE THREAD

**Issue by weepingminotaur** [WBHarry/pf2e-bestiary-tracking#61]
Just wondering if something changed after the 0.8.9.9.2 release, which was the last one to hit the Forge. I see that there have been many updates since then but none are showing up on the Forge at this moment.

**Comment by WBHarry** [comment]
Hm. I just pushed out v.0.8.12 with some bugfixes.

Forge seems to be weird about getting the versions right. Don't really know what's up with that 😓

**Comment by weepingminotaur** [comment]
Yeah, I confirmed with Forge that it seems to be an issue on their end affecting module updates pushed out today.

**Comment by WBHarry** [comment]
That's good to hear from my end at least. Means I don't have to try and look into it just yet 😄
