### ISSUE TITLE
Player sees nothing in bestiary on most tabs

### ISSUE THREAD

**Issue by mgoldstein322** [WBHarry/pf2e-bestiary-tracking#62]
Hi again! I just finished getting all my data back into the bestiary after resetting it with the script you gave me, and I was asking one of my players to show me what he sees. When he clicks on tabs that have monsters in them (except for the fungus tab), nothing happens. Clicking on tabs with no monsters in them displays the "nothing encountered yet" page.

I just updated to 0.8.14 and ran the script that you sent me to reset the bestiary when I was unable to open it.

Attached video shows his perspective.

[Bestiary Broke.webm](https://github.com/user-attachments/assets/c9e0547a-1ca9-467e-a29f-bbcfb6bcd99f)

**Comment by WBHarry** [comment]
A bit hard for me to tell from the video, but it might not be a bug at all.

If you haven't revealed any creature traits on a creature, it will be sorted in the **Unknown** category, since they don't know what it is. The fungus probably shows up there because you have revealed the Fungus trait. The GM always sees creatures in their actual categories.

Check if that's the case.

**Comment by mgoldstein322** [comment]
Yeah the video is super low-res haha.

I did check that to see why that creature was unknown to him, and after revealing it (it would have been visible under humanoid), he was still unable to access the humanoid tab.

To be clear, the issue isn't that the tabs don't show anything, it's that clicking on them doesn't do anything. I have no idea what they show to him because the application doesn't do anything at all when they're clicked on.

But yes, just to confirm, I have many creatures and their traits revealed:

![image](https://github.com/user-attachments/assets/6e63e972-b00c-49c9-bb39-b05d561f71ad)

**Comment by WBHarry** [comment]
Hm..what browser is he using? The video is a bit to grainy for me to tell if it's actually Chrome or something else.

**Comment by mgoldstein322** [comment]
Firefox, as am I.

**Comment by WBHarry** [comment]
Hm. No things seem fine on Firefox for me at least. I've never seen something like this happen before.

It would be good if he would try it on Chrome just to see if the issue persists.
------
If that doesn't do anything, then I would have to see some errors that must be showing up on his side in the console. 

If there really are no errors in the console or they don't end up telling me anything, then the only thing to do would be to zip up the gameworld where things are going wrong and send it over to me on discord.

You can spot me easily in this module's thread on the Pathfinder Discord (I have the same avatar picture)
https://discordapp.com/channels/880968862240239708/1273006578357764096

**Comment by mgoldstein322** [comment]
My friend says it works fine on Chrome.

He gets this error when he tries to open it in Firefox:
![image](https://github.com/user-attachments/assets/d5308824-d7fc-483e-a170-361d070c4403)

**Comment by WBHarry** [comment]
I just released v0.8.15. I did add a small thing that might make it work for your friend, but I'm not entirely sure since I can't test it.

Firefox isn't really reccomended for Foundry - but that being said, things work fine on base Firefox for me. It might be that your friend is using some firefox addons that mess with things. Hard to say 🤔

**Comment by mgoldstein322** [comment]
I'll get him to try it out soon and let you know!

And yeah... I know FF isn't really recommended but we're all chrome haters lol

**Comment by mgoldstein322** [comment]
Just got the chance to have him try it out, and it looks like it's fixed :)
