### ISSUE TITLE
[Bug] Picture Name

### ISSUE THREAD

**Issue by Crowguard** [WBHarry/pf2e-bestiary-tracking#64]
The picture name doesn't respect the visibility and tells the players.

![chrome_j1SUpbGUhf](https://github.com/user-attachments/assets/85865a82-68eb-4971-938e-48b0b2443db7)

Bestiary 0.8.15

**Comment by WBHarry** [comment]
I just released v0.9.0 with the first rendition of the NPC Gallery. I also included a fix so that the correct name state is shown in the popout picture :grin:
