### ISSUE TITLE
[Feature Request] Add support for NPCs stat blocks as in the Influence Subsystem

### ISSUE THREAD

**Issue by scari08** [WBHarry/pf2e-bestiary-tracking#65]
There's a subsytem in the game that supports a more granular way to track the disposition, weaknesses, resistances, etc of most important NPCs (these are more "social" stats, especially with skills support, than actual combat stats).
Maybe in a new tab called "Influence", it would be cool to have the more specific stat block for the influence subsystem.

**Comment by WBHarry** [comment]
Yup, this is getting added among other things 😁

**Comment by WBHarry** [comment]
I made a little paint outline of it as the first view I thought about, actually
![image](https://github.com/user-attachments/assets/a4f54cc9-f439-4630-86a4-a69c02d1e29d)
