### ISSUE TITLE
[Enhancement] Ability to set what is auto-revealed for monster when first added to bestiary

### ISSUE THREAD

**Issue by weepingminotaur** [WBHarry/pf2e-bestiary-tracking#66]
Generally, I like to provide monster name, type/level, saves, and lore on the first successful RK check. Would be great if you could specify what should be auto-revealed the first time a monster is added to the bestiary, so we then don't have to go through and manually reveal a bunch of things.

**Comment by WBHarry** [comment]
Good idea. Just have to figure out where I want to put this module setting 😁 👍

**Comment by WBHarry** [comment]
I just released v0.9.5. It adds this as a feature 🤖 ✌️ 
![image](https://github.com/user-attachments/assets/0e808219-772e-46a1-9ad8-1092134d8a2e)
