### ISSUE TITLE
[BUG] Double-click to open bestiary is inconsistent for players

### ISSUE THREAD

**Issue by poindexter1985** [WBHarry/pf2e-bestiary-tracking#68]
This was [discussed briefly on Discord](https://discord.com/channels/880968862240239708/1273006578357764096/1280229323072213052), and the source of the problem hasn't been narrowed down. Possibly related to Item Piles conflict.

Repeating the same info here to keep track of this as an issue for later.

![image](https://github.com/user-attachments/assets/bef14aac-7f5d-4ed9-a394-660303df0aa4)

**Comment by WBHarry** [comment]
Hm. I tried it with the Cinder Rat and the Juvenile Horned Dragon and they work fine for me.

Just to be sure,
Players can't get any response from double clicking unless the creature is added to the Bestiary - while GMs will still get a notice message that the monster isn't in the Bestiary.
A player has to have at least Ownership level of 'Limited' over a creature to be able to get a response to double clicking, and thus open the Bestiary. I do automatically set this when the setting is enabled - but maybe you've lowered their ownership level manually?

**Comment by poindexter1985** [comment]
I did check at the time that All Players was limited, and individual players were Default.

After upgrading the module version to 0.9.4, there was no immediate change in behaviour. I reset the bestiary, and re-added all of the creatures. After doing so, the Juvenile Horned Dragon still did not work, but it worked for all other tokens I had on the scene. The cinder rat, which had previously not worked, now does.

I tried removing the dragon's token, and put a new one on the scene. Double clicking the new token worked fine. Currently, it's working for everybody. I'll continue to observe and make note if I find any other instances of it not working.

**Comment by WBHarry** [comment]
Hmmmmm...I'm struggling to come up with a reason for the observed behavior, but yes, please do bring it up again if something weird happens.
Because of the new version and data model, I'm going to close this issue since it is working at the moment. But feel free to open a new issue if the issue rears it's head again 😄
