### ISSUE TITLE
[Feature Request] Reveal Fields by Default

### ISSUE THREAD

**Issue by ByronThompson** [WBHarry/pf2e-bestiary-tracking#69]
It would be nice to be able to select certain fields to be revealed by default when a creature is added to the Bestiary, namely the creatures Name, Traits, and Description, but I'm sure others could find use in revealing things like saves or abilities

**Comment by WBHarry** [comment]
I just released v0.9.5. It adds this as a module setting 😁 👌 
![image](https://github.com/user-attachments/assets/4a96b398-34f1-4a43-a15d-f06a55d4ddcf)
