### ISSUE TITLE
[Feature] Option to Obscure Name

### ISSUE THREAD

**Issue by ChasarooniZ** [WBHarry/pf2e-bestiary-tracking#7]
For when your characters don't know the creature name or they misidentify it etc.

**Comment by WBHarry** [comment]
The current verison 0.8.3 hides creature names by default, and the GM can then reveal them. When they're hidden, they're shown as 'Unknown Creature'.

Missidentifying is a larger issue that I might tackle in some upcoming version by allowing a GM to write something custom for fields to missidentify it.

**Comment by apoapostolov** [comment]
I was coming to suggest the same thing, but with option to have a custom replacement name i.e. "The Evil Fairy" that is actually a Seelie Banelight.

**Comment by WBHarry** [comment]
Version 0.8.4 had added the ability to set missinformation on the creature name. Considerign this closed. 😁
