### ISSUE TITLE
Error in prepareBestiary when attempting to open the bestiary

### ISSUE THREAD

**Issue by samerogers** [WBHarry/pf2e-bestiary-tracking#70]
I run into consistent errors whenever I try to open the bestiary from any of the supported means. This is running in Foundry v12 build 331 (also tried 330) with PF2e version 6.3.1. Advanced Macros and lib-wrapper versions included in the screenshots. The issue happens on both Firefox and Chrome. I suspect that the issue might have arisen from some bad migration data from an older version of the module. If I can figure out which files to purge I can see if that resolves the issue at least on my end.

Migration Error
![image](https://github.com/user-attachments/assets/3fe6ab3f-f018-4fd9-9dc0-3e17c101ad6f)

Hotkey
![image](https://github.com/user-attachments/assets/ef4ddaa7-8c68-43d1-9c1f-973dccff2e3f)

Macro
![image](https://github.com/user-attachments/assets/96053546-3ec6-439e-a57f-712224766db3)

**Comment by samerogers** [comment]
Issue arose when I updated from 0.8.9.6 to anything newer than 0.9.0. Going to the last 0.8.x release, I can open the bestiary, but all entries are broken. I'll try incremental upgrades to see where things start working again, but this is kind of insane for essentially a week between updates.

**Comment by WBHarry** [comment]
Well, as far as a week between updates - a lot has happened as I've been spending a crazy amount of time on this 😆 

The issue you're running into is probably -very- complex. The thing is that I had a bad missunderstanding of how Foundry handles a certain quirk of databases (really doesn't make sense to me, but here we are). It caused migrations to be ignored, which could put users into bad states.

I can tell from the error messages that your data is quite mixed up.
It's not a happy solution, but I would recommend using the `Reset Bestiary` macro. It'll get everything working on the updated setup, losing any creature entries that had been added.

Now that migrations can work properly, things should be good moving forward 🤞

**Comment by WBHarry** [comment]
I just released v0.9.5 that makes the `Reset Bestiary` macro even more fullproof.
