### ISSUE TITLE
Question: NPC tabs, how to assign NPCs to different Tabs

### ISSUE THREAD

**Issue by Mermut** [WBHarry/pf2e-bestiary-tracking#71]
We can create different tabs for the NPC directory, but all NPCs automatically go to the unaffiliated tab and I can't figure out how to move them...

EDIT: Nevermind, I figured it out.. it's on the NPC listing IN the bestiary

**Comment by WBHarry** [comment]
Yup! There's a lot to improve and wiki information to add regarding the NPC Gallery.
It was a very barebone release, and I've been very busy with data model changes since then so I haven't been able to improve on it like I wanted to yet.
