### ISSUE TITLE
Unique creatures moved to NPC section

### ISSUE THREAD

**Issue by Mermut** [WBHarry/pf2e-bestiary-tracking#72]
Despite having the NPC section set to use the NPC tag, a number of creatures that had the Unique tag have been moved from the bestiary section to the NPC section with the 0.9.5 update.
1) I can't see any way to put them 'back' without deleting and re-adding them
2) doing the above loses all the revealed information

**Comment by WBHarry** [comment]
That's curious, I didn't do any migrations moving anything.
There is a way to move them though, an explicitly added feature in 0.9.5. 
![image](https://github.com/user-attachments/assets/81f9d51b-e929-4989-96c6-21fc7b81a36b)

Transform to NPC to creature and all.

**Comment by WBHarry** [comment]
Oh, right, I get it. You must have uppgraded at least 2 versions at once.

I did make a move in 0.9.4 where I moved all creatures that were either Unique or had NPC tags from the creature side to the NPC section. My thinking was that these would be entities that should be in the NPC section before it existed

I realise now that wasn't neccessarily correct. But but. Should be easy to move them at least now 😁

**Comment by weepingminotaur** [comment]
Glad I checked this issue before logging a bug. Just had the same issue. Added two unique monsters to the bestiary, couldn't find them, but they registered as having been added since there was no longer an option to add them to bestiary in the contextual menu in the sidebar. They had indeed been added to the NPC Gallery. I moved them back.

**Comment by WBHarry** [comment]
With the bugfix versions released I'm quite certain this issue is solved. Otherwise feel free to open a new issue 🤖 👌
