### ISSUE TITLE
Bug? Right clicking on an NPC Category removes all other categories

### ISSUE THREAD

**Issue by Dom-Odyssey** [WBHarry/pf2e-bestiary-tracking#73]
When i right click on an NPC Category on the left side of the bestiary menu it removes all other categories other than the one right clicked on. All NPC in the categories that were removed cannot be readded to the bestiary.

I think the data is still there but there might be an error with showing it or accessing it.

![image](https://github.com/user-attachments/assets/c5b59a25-6228-42a9-b28b-3f069ee9d8ab)

Then if i right click on cata 3
![image](https://github.com/user-attachments/assets/6ea63ac0-ee90-43eb-b6dc-ea3b85a505f3)

This might double as a feature request to have a way to remove or hide NPC categories so you can set up influence stuff ahead of time without a player knowing the category exists.

**Comment by WBHarry** [comment]
I've fixed the bug in my dev verison and I'm going to push out a bugfix patch for a few things quite soon.

As for the feature requests it's a good idea. It's very in line with how you can hide that an NPC is part of a category now.

**Comment by WBHarry** [comment]
I just released v0.9.8. It includes the ability to hide NPC categories. Just hover the bookmark and click the eye.🤖 ✌️ 
![image](https://github.com/user-attachments/assets/1b7c42c6-3ebb-4da5-afed-f75ef740648d)
