### ISSUE TITLE
[Enhancement] Better placement of "return to [category] page"

### ISSUE THREAD

**Issue by weepingminotaur** [WBHarry/pf2e-bestiary-tracking#74]
Right now, the "Return to [category] page" (Aberration, Construct, etc.) is all the way to the right, just northeast of the Notes section. It's not aligned properly, it looks weird where it is, it's too close to Notes -- you could click the latter accidentally -- and it doesn't match where the "Return to the main page" button is (top left). I suggest putting the return to category button in roughly the same location as the return to the main page button: top left, perhaps above the monster image.

Also, for concision, "Return to main page" is probably better (no "the" needed).

**Comment by WBHarry** [comment]
Yup, I've been aware it's in an akward spot. I've been loathe to move it to the same place though, because it means all the content has to be shifted down to accomodate which I never quite liked.
![image](https://github.com/user-attachments/assets/a1505fdb-81eb-43d8-8e61-6f0bded09572)

**Comment by WBHarry** [comment]
But, it does look a lot better. I'll move it up there.
Less of an issue now aswell since you can resize the window

**Comment by WBHarry** [comment]
I did the the thing. Version 0.9.7 out with the change. 🤖 ✌️
