### ISSUE TITLE
[Feature Request] Recall Knowledge Rules

### ISSUE THREAD

**Issue by Crowguard** [WBHarry/pf2e-bestiary-tracking#76]
A way for the GM to either modify the main screen text themselves, or just a way to link to link to a journal on the main screen (would prefer this one myself) that the GM can keep updated with their own rules for how they choose to run Recall Knowledge.

I play in three different games and run my own, and we all have slight variations on how we handle RK; this would let players quickly double check things.

![image](https://github.com/user-attachments/assets/560a1305-d214-4a1a-ac70-e4472d568a2f)

**Comment by WBHarry** [comment]
The feature is done on the dev branch. Pushing it out when I make the next version 🤖 👍 
https://github.com/user-attachments/assets/bb2b7dbb-1f6c-4a60-8f1b-03ceee2b391d

**Comment by WBHarry** [comment]
I just released v0.9.8 and it includes this features 🎉
