### ISSUE TITLE
[Feature Request] Allow an actor to exist in both the Bestiary and NPC Gallery simultaneously

### ISSUE THREAD

**Issue by RavenRaconteur** [WBHarry/pf2e-bestiary-tracking#77]
There are some actors where I'd like to be able to reveal both combat statistics in the Bestiary as well as track their roleplay details as an NPC in the gallery. Is this a possibility?

**Comment by WBHarry** [comment]
It currently works that way. If you add an NPC, then it's combat statistics can be viewed. (short clip below)

https://github.com/user-attachments/assets/1b80557d-23e5-478d-a5f7-962b523c5606

In this case I didn't set up any stats or stuff on this one. But NPCs have everything creatures have, and a little extra. 🤖 👌
