### ISSUE TITLE
[Feature Request] Quickly add a creature to NPCs

### ISSUE THREAD

**Issue by TiloBuechsenschuss** [WBHarry/pf2e-bestiary-tracking#79]
There is currently no way I've found to quickly add a creature as an NPC. You have to drag in a creature, then go to the category it's in, open it, and convert it to an NPC.
Ideally the module could always add creatures to NPCs if the NPC category is open. If that is too tricky, maybe a different way like a dedicated drop zone for NPCs. Or a keybind, like holding CTRL while dropping a creature.

**Comment by WBHarry** [comment]
There is a way to quickly add an NPC. Converting is more of a utility incase something needs to be fixed, generally.

By default, if you drag in an actor that is Unique, then it is added as an NPC. You can change this in the module settings to instead signify NPCs by adding an NPC tag to Actors.
![image](https://github.com/user-attachments/assets/26fe49a3-786e-4bd3-85a7-6aa0b0ef55fc)

**Comment by TiloBuechsenschuss** [comment]
Oh, I see. I'm really bad about adding Unique tag to my NPCs, since they're mostly recycled from other stat blocks (with some modification, perhaps). But that should work for me, thanks!
