### ISSUE TITLE
[Feature Request] Option to List Spellcaster Categories and Spells

### ISSUE THREAD

**Issue by apoapostolov** [WBHarry/pf2e-bestiary-tracking#8]
The ability to reveal specific spellcasting categories (i.e. Primal Innate Spellcaster) and the ability to reveal individual spells that the players saw cast when first encountering this creature. The spellcasting catregory could reveal absolute or subjective DC and spell attack modifier.

**Comment by weepingminotaur** [comment]
Definitely seconding this request.

**Comment by WBHarry** [comment]
I just released v0.8.7. It adds a Spells tab to the creature view where traditions and their spells can be revealed, along with their DC and Attack Modifier (which can be subjective).
![image](https://github.com/user-attachments/assets/9dbcac13-0fc6-48fc-a1be-7531b530b307)

**Comment by apoapostolov** [comment]
Thank you!!
