### ISSUE TITLE
[enhancement] Option to hide Art in browser/sheet

### ISSUE THREAD

**Issue by Iankid** [WBHarry/pf2e-bestiary-tracking#80]
An option to hide the art of a creature/NPC in the browser and sheet.
My suggestion would be two or three options for hiding. completely no art visible, silhouette, or maybe a custom "unknown" image.
I can see this being useful for Creatures/NPCs the party has heard of, but not actually seen yet.

**Comment by WBHarry** [comment]
I pushed out v1.0.2 that adds Avatar Filters as a feature along with module settings to set the default filters desired for the different types of entries in the Bestiary. 🤖 ✌️ 
![image](https://github.com/user-attachments/assets/b88ef7f3-d04f-4ed9-bf5f-283676a28708)
![image](https://github.com/user-attachments/assets/e1d5b6a1-6d8b-488e-9328-2128022abec7)
