### ISSUE TITLE
[Enhancement] NPC categories should defualt to hidden when created

### ISSUE THREAD

**Issue by Iankid** [WBHarry/pf2e-bestiary-tracking#81]
Like the new hidden state for NPC categories. However, if players happen to be in server when the GM it messing with categories, there's a chance the players could see a newly created one currently, before the GM has a chance to hide it.

**Comment by WBHarry** [comment]
I just released v0.9.9. Categories are now hidden by default. It can be changed to default reveal in a module setting if desired 🤖 ✌️
