### ISSUE TITLE
[Enhancement] Update/change actor source for NPCs

### ISSUE THREAD

**Issue by Iankid** [WBHarry/pf2e-bestiary-tracking#82]
Allow a GM to change the source Actor for an NPC in the bestiary.
Useful for if an NPC gets stronger, or changes stats, over the course of a campaign, but player notes, dispositions, and other bestiary central stats want to be retained.

Failing the above, perhaps an option to link multiple NPC bestiary entries.

**Comment by WBHarry** [comment]
Hm. Wouldn't this be handled by the current refreshing?
Is there a need to completly changed Actor instead of just editing the existing and refreshing? 🤔

**Comment by Iankid** [comment]
I work with Metamorphic Studio, And obviously we have to give GM's the actor for each version of an NPC if they've changed over the course of an adventure. plus, it's not to hard to imagine a GM doing the same themselves.

**Comment by Iankid** [comment]
Another potential use of this I was just realizing (looking at a campaign I'm prepping), is NPCs that have basic creature stats. Perhaps then this could make it so the GM doesn't have to re-reveal attributes/features if players already revealed stats on non-named NPCs in the bestiary.

**Comment by WBHarry** [comment]
I just released v1.1.4 and it adds both solutions.
- In the Actor Link Menu you can remove the current actor from a Bestiary Entry and substitute in another.
- You can also add additional linked actors in this menu that you can then swap between. Only the active one is visible in the Bestiary.
![image](https://github.com/user-attachments/assets/4bc41a2e-ca14-4c81-a2ea-ac327565bda4)

**Comment by WBHarry** [comment]
The later mentioned of using the same statblock for different named NPCs can be handled via Duplicate Actors aswell. 
Make an Actor like `Guard Captain`, then add your named people like `Captain Bhurt` as duplicate actors to it. Then those named actors will point to the generic entry in the Bestiary when you doubleclick it and so on.
