### ISSUE TITLE
[Bug] Can't access NPC Gallery, creature types breaks

### ISSUE THREAD

**Issue by Keatnisher** [WBHarry/pf2e-bestiary-tracking#83]
I can access the creature tabs and add creatures as usual, until I try to click on the NPC gallery tab, then I receive this error:

![image](https://github.com/user-attachments/assets/28a2d592-8063-41ae-9839-68ae943698c9)

Then none of the buttons work:

![image](https://github.com/user-attachments/assets/22d7778c-e3cf-4134-9d8f-369d2e1822c1)

**Comment by WBHarry** [comment]
I just released v.0.9.9. I think that should solve this issue 🤖 👍

**Comment by WBHarry** [comment]
Hoping this worked out. Closing the issue due to inactivity. Feel free to open another issue if something still won't work.
