### ISSUE TITLE
[Major Bug] Some categories vanish when changing order

### ISSUE THREAD

**Issue by Iankid** [WBHarry/pf2e-bestiary-tracking#84]
Several of my NPC categories are now gone. however looking at those that exists with NPCs with multiple categories, I can see they still technically exist.
Categories with NPCs with only the one category I can no longer access, and I cannot add them into the bestiary, so they are still registered in the missing category.

**Comment by WBHarry** [comment]
Are you on the latest version? I did fix a bug related to exactly this.

**Comment by Iankid** [comment]
literally just updated before this.

**Comment by Iankid** [comment]
yeeeep, just double check version and messed with it more. now all my categories are gone.

**Comment by WBHarry** [comment]
Hm. I just tried making a bunch of categories and dragging things around like a maniac, and I haven't been able to trigger any categories disappearing. 🤔 

All you're doing is making a bunch of categories, and then trying to reorder them?

**Comment by Iankid** [comment]
whatever the bug is, it's getting worse. Now I can't even give new NPCs a category. I did see briefly "item piles" in the console in related to the errors. but I can't look back at it now.

**Comment by WBHarry** [comment]
Item Piles has shown some conflict with the module before, although I doubt it would effect this.

**Comment by Iankid** [comment]
either way, I'm thinking I gotta nuke this bestiary.

**Comment by WBHarry** [comment]
Reset Macro will definately get it right again. Hmn..don't really have any leads as to how it ended up in that state though 🤔

**Comment by Iankid** [comment]
Ok, got a repeatable example. it's not limited to this, so not sure what makes this combo repeatable specifically.

https://github.com/user-attachments/assets/d949ee22-c85f-4fb8-8977-639c00b6c2f3

**Comment by WBHarry** [comment]
Hm. I'll enable Pathfinder UI and see if I can get that to happen to me.

As a note - I just pushed out a new version because I realised that I needed to add a new thing to the Reset Bestiary macro. Just so you know for when you go that route.

**Comment by WBHarry** [comment]
Alright, I've found the bug. It happens if you go precisly one step up when you reorder. I'll sort that out 👍

**Comment by WBHarry** [comment]
I just release v0.9.13 that adds a fix for this bug. It also does a migration that should return any NPCs that got hidden - placing them in the Unaffiliated category. 🤖 ✌️
