### ISSUE TITLE
Can't open tracker

### ISSUE THREAD

**Issue by bsleys** [WBHarry/pf2e-bestiary-tracking#85]
I get the following error when trying to open the bestiary tracker in one of my games.

BestiaryTracking.js:9644 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'getFlag')
[Detected 1 package: pf2e-bestiary-tracking(0.9.12)]
    at PF2EBestiary.sharedPreparation (BestiaryTracking.js:9644:52)
    at PF2EBestiary._prepareContext (BestiaryTracking.js:9586:26)
    at async #render (foundry-esm.js:44319:23)
    at async Semaphore._try (foundry-esm.js:6645:19)

Is there is way to force reset the data?  I'm guessing something didn't migrate over properly.

**Comment by WBHarry** [comment]
Heya. Yeah, your bestiary has clearly gotten stuck on an old model for some reason.
Easy way to get up to speed again is to use the `Reset Bestiary` macro. It'll clear out data and set up the model as it should be.
![image](https://github.com/user-attachments/assets/50a58337-0da0-4fe9-ab2d-18adf2296d6c)

**Comment by WBHarry** [comment]
**Breaking News**
If you haven't already run the reset, try updating to 0.9.14. It solved this issue for someone else, so it would assumably do so for your world too 🤖

**Comment by WBHarry** [comment]
Hoping this got fixed! Feel free to open another issue otherwise. I'm closing this one due to inactivity. 🤖 ✌️

**Comment by bsleys** [comment]
Yes I was able to reset the data just fine.  Thanks for you quick update and forgive my late replay.

Bob
