### ISSUE TITLE
[Feature Request] Linking to Entries

### ISSUE THREAD

**Issue by CGarciaRomo** [WBHarry/pf2e-bestiary-tracking#86]
It would be nice to have a way to link any entry (Creature, NPC or Hazard) to a text editor, just as one would link other journals, actors, items, etc. Clicking on the link would open the bestiary tracker directly on the linked entry.
This would be very helpful for cross-referencing between journals and the bestiary tracker.

**Comment by WBHarry** [comment]
I just released v1.0.3 that adds this feature 🤖 👌 
![image](https://github.com/user-attachments/assets/f46b2a58-93bf-462b-9e93-654aedd9245a)
Button adds the link to your clipboard so you can paste it in the same way you work with sheets.
