### ISSUE TITLE
[enhacement] improve influence weakness/resistances toggle clarity

### ISSUE THREAD

**Issue by Iankid** [WBHarry/pf2e-bestiary-tracking#88]
There's the chance I misunderstood this myself, but that just confirms the issue.
From setting up a character for influence, this appears to be the "default toggle states" where neither the weakness or resistance is in play.
However, the activation button being opposite makes that confusing.
![image](https://github.com/user-attachments/assets/ee5a20e6-6ce0-46ae-bd97-8d45c191f2f0)

**Comment by WBHarry** [comment]
I think the main culprit here is that Pathfinder UI is applying it's standard style here, and it's making it less clear. This is how it looks standard between an activated and unactivated weakness/resistance.
![image](https://github.com/user-attachments/assets/38ce0f98-c8fa-4d03-aade-bbc130f3d765)

**Comment by Iankid** [comment]
oh there is a different bug going on then. changed numbers, and both toggled on 
![image](https://github.com/user-attachments/assets/28696d3d-e1be-4e00-8820-405e450709eb)

**Comment by WBHarry** [comment]
Ah, good catch. I misstakenly inverted the logic in the Resistance case specifically. I'll fix that 👍

**Comment by WBHarry** [comment]
I pushed out v1.0.1 as a bugfix patch. Corrected this 🤖 👍
