### ISSUE TITLE
[feature request] toggle influence reward visibility

### ISSUE THREAD

**Issue by Iankid** [WBHarry/pf2e-bestiary-tracking#89]
Sometimes there are influence rewards that don't have an immediate effect for the players, or are secret for some other reason, and thus shouldn't be visible, as it can cause spoilers. A visibility toggle for each reward tier would be appreciable for this case.

**Comment by WBHarry** [comment]
You can set up different rewards, unless I'm missunderstanding what you mean.
![image](https://github.com/user-attachments/assets/620e64f6-4938-484b-a108-36f479d72527)

Every Influence Reward you set up is individually revealable.

**Comment by Iankid** [comment]
They reveal as influence climbs, yes. But say in your image they reach influence 6, but I don't want then to see "something unknown" until a later story point. currently it will still reveal it.

**Comment by WBHarry** [comment]
Alright, so you mean multiple different things at level 6. 
Hm. That is possible case, yup. Originally I just made them clickable to reveal which would have worked for this, but I thought it was fancy to bind it directly to the climbing influence at the time.

**Comment by WBHarry** [comment]
I pushed out v1.0.1 as a bugfix patch. Influence rewards are now revealed by clicking on them as other things are 🤖 👍
