### ISSUE TITLE
Fix needed for Larger Entries

### ISSUE THREAD

**Issue by ThomaSutra** [WBHarry/pf2e-bestiary-tracking#9]
In using the Mod in a game, I noticed that when I add a creature with a large amount of information, I am unable to see or access the bottom of the creatures sheet. 

Please add a scroll bar so we can access the bottom of sheets that are too long for a browser window. 

Thanks

PS. LOVE this Module! Thank you for creating it

**Comment by WBHarry** [comment]
I just released v.0.8.6. It does a lot to help with the styling issues that were going on. There are scrollbars where there should be, and overall it should be much better.
There are still some oddities when there are attacks on a creature with a ton of traits on them, but it doesn't ruin the rest of the creature view anymore.

I'll keep this issue open for now and return to it when things change or more oddities are found.

**Comment by WBHarry** [comment]
I just released v0.8.7.1. I'm feeling quite sure that large entities will break the styling anymore.
I'm closing this issue, but feel free to open another one if you notice something still displaying weirdly. 🫶
