### ISSUE TITLE
[feature request] Option to have influence tab toggled off by defualt

### ISSUE THREAD

**Issue by Iankid** [WBHarry/pf2e-bestiary-tracking#91]
currently any newly add NPCs have the influence tab visible. however most NPCs won't make use of that tab, and may give players incorrect assumptions. (having to manually toggle each of them off right now)

**Comment by WBHarry** [comment]
I pushed out v1.0.1 as a bugfix patch. It sets the default to be hidden as it should have been 🤖 👍
