### ISSUE TITLE
[feature request] confirmation on category deletion

### ISSUE THREAD

**Issue by Iankid** [WBHarry/pf2e-bestiary-tracking#92]
thankfully haven't done this much yet. but with it just being a right click to delete categories, I can see this being a fairly easy mistake to make.

**Comment by WBHarry** [comment]
Hm. People always dislike confirmation windows..but I suppose this shouldn't be something you do very often, so maybe it's fair to add one.

**Comment by WBHarry** [comment]
I pushed out v1.0.1 as a bugfix patch. It adds this 🤖 👍
