### ISSUE TITLE
[bug] NPCs seems to be limited to 4 affiliations

### ISSUE THREAD

**Issue by Iankid** [WBHarry/pf2e-bestiary-tracking#93]
attempting to add more then 4 affiliations makes the drop down bug then disappear.

Edit: seems to be more an issue with the width of the bar, and available space on the end
![image](https://github.com/user-attachments/assets/2d4aead8-02a1-441d-bd2f-7a14109e4932)
Also doesn't wrap around well.

**Comment by WBHarry** [comment]
Ah, it's not related to the amount of affiliations, but it's when the combined width reach towards the end of the input. I'll see if I can fix that up.

**Comment by WBHarry** [comment]
I pushed out v1.0.1 as a bugfix patch. It fixes this 🤖 👍
