### ISSUE TITLE
[Bug] NPC View Toggle crashes bestiary window

### ISSUE THREAD

**Issue by Iankid** [WBHarry/pf2e-bestiary-tracking#94]
Pressing the button is crashing the bestiary window, with a long render error in the console.
https://github.com/user-attachments/assets/40fb4c7e-23e7-4609-a7bf-f1dae601f078

**Comment by WBHarry** [comment]
Ah. I forgot to check the NPC variable in the new rendering with Hazards. Just got to put it in there.
Thanks for finding this 😄

**Comment by WBHarry** [comment]
I pushed out v1.0.2 that includes the little fix for this 🤖 👍
