### ISSUE TITLE
[Bug] Creature Actors end up in the NPC Gallery

### ISSUE THREAD

**Issue by tagnullde** [WBHarry/pf2e-bestiary-tracking#96]
My Players defeated some "Chew Spiders". After reviewing it in the Creatures-Tab, it wasn't shown. Instead it was added to the NPC Gallery. I would have expected it to be in the Creature section.

![image](https://github.com/user-attachments/assets/8182c6f5-c89a-432a-9f83-d753775f58da)

I noticed that not every actor can be placed "here or there". This is sort of unfortunate limitation right now too.
Since some NPCs are technically "Monsters". Like "Perlivash" for example needs to be in the Creature section although it should be unter NPCs. Especially in the Kingmaker AP some NPCs have full PC-Sheets but can't be placed in the NPC section because of it. Those would benefit from the newly introduced "Influence" tab the most.

This "Bug" report is kind of a mix of Bug-Report and Feature Request. ;)
Chew Spiders shouldn't be a NPC, while other Actors would benefit of being either or.

**Comment by WBHarry** [comment]
Iankid's got it. 👍 

At the moment, it doesn't matter which section of the Bestiary you have open - Actor's being dropped in are placed in sections based on their properties.

-------
Hazards always go into the hazards category.
Creatures and NPCs are the same actor type (NPC), so by default I distinguish that Unique NPCs should go to the NPC Gallery - but you can indeed switch that behavior to instead tag them with an NPC trait.

**Comment by tagnullde** [comment]
Oh. Ok I see. Thanks for the Headsup. I fixed so far for me.
The only thing that won't work is to add Actors to the NPC Gallery that are "Players" even with a NPC Tag.
But this might be outside of the scope of this mod and not actually be needed in practice. 

![image](https://github.com/user-attachments/assets/5a7ee0a5-77dd-4961-b049-3fe1151cf1bb)
![image](https://github.com/user-attachments/assets/6a18c4cd-aeb2-4ba8-ac72-9459bfa12fa9)

Thanks for the help.

**Comment by WBHarry** [comment]
It's something that's been suggested before, and something I probably will look into. It shouldn't take that much change to let a PC be imported.
