### ISSUE TITLE
[Enhancement] Rename Abilities section to Actions

### ISSUE THREAD

**Issue by weepingminotaur** [WBHarry/pf2e-bestiary-tracking#97]
This renaming would bring the section into alignment with what is already on the actor sheets for monsters and NPCs. Everything in the Abilities section is an action, as distinct from Passives (things that are just on by default).

**Comment by WBHarry** [comment]
Yup, makes sense. I made this change with the release of v1.0.3.

In the data model, Attacks are actually called Actions, which is part of why it ended up this way in my brain to differentiate 😁
